PACKAGE	= listings

TMPINPUTS=listings.cfg lstdoc.sty lstlang1.sty lstlang2.sty lstlang3.sty lstmisc.sty
TMPDOC=$(PACKAGE).dvi
EXTRADOC=README
EXTRAINPUTS=lstpatch.sty

include ../make.rules
JUNK=lstdrvrs.ins
